### ISSUE TITLE
 (theano error) configparser.NoSectionError: No section: 'blas'

### ISSUE THREAD

**Issue by bmilde** [uhh-lt/subtitle2go#5]
[…]
    
    LOG (ivector-extract-online2[5.5.950~1-085be]:main():ivector-extract-online2.cc:194) Average iVector length was 12.8959 and at utterance-end was 14.2856, over 19092 frames (weighted);  expected length is 10
    
    WARNING ([5.5.950~1-085be]:CompactLatticeToWordAlignment():lattice-functions.cc:1009) Lattice has alignments on final-weight: probably was not word-aligned (alignments will be approximate)
    
    removing tmp file: tmp/1e3ba3abebaecccf.scp
    
    removing tmp file: tmp/1e3ba3abebaecccf.wav
    
    removing tmp file: tmp/1e3ba3abebaecccf_spk2utt
    
    LOG ([5.5.950~1-085be]:~CachingOptimizingCompiler():nnet-optimize.cc:710) 0.00878 seconds taken in nnet3 compilation total (breakdown: 0.00566 compilation, 0.00188 optimization, 0 shortcut expansion, 0.000389 checking, 1.91e-06 computing indexes, 0.000849 misc.) + 0 I/O.
    
    Starting interpunctuation
    
    Traceback (most recent call last):
    
      File "/home/nutzer/projects-2022-04-06/subtitle2go/subtitle2go_env/lib/python3.9/site-packages/theano/configparser.py", line 168, in fetch_val_for_key
    
        return theano_cfg.get(section, option)
    
      File "/usr/lib/python3.9/configparser.py", line 781, in get
    
        d = self._unify_values(section, vars)
    
      File "/usr/lib/python3.9/configparser.py", line 1152, in _unify_values
    
        raise NoSectionError(section) from None
    
    configparser.NoSectionError: No section: 'blas'

This is a Theano error with Python 3.9 and newer numpy versions. I've posted this to the Theano project: https://github.com/Theano/Theano/issues/6788

A hot fix for this problem is replacing this in line 1284 in theano's configdefaults.py:

             blas_info = np.distutils.__config__.blas_opt_info

            =>

            blas_info = np.distutils.__config__.blas_ilp64_opt_info

**Comment by bmilde** [comment]
Closing this, since we don't use theano anymore.
